#+TITLE: 5.4 - The Explicit-Control Evaluator
#+STARTUP: indent
#+OPTIONS: num:nil
#+PROPERTY: header-args:scheme :tangle yes

#+BEGIN_QUOTE
With the implementation of the explicit-control evaluator we come to
the end of a development, begun in Chapter 1, in which we have
explored successively more precise models of the evaluation
process. We started with the relatively informal substitution model,
then extended this in Chapter 3 to the environment model, which
enabled us to deal with state and change. In the metacircular
evaluator of Chapter 4, we used Scheme itself as a language for making
more explicit the environment structure constructed during evaluation
of an expression. Now, with register machines, we have taken a close
look at the evaluator’s mechanisms for storage management, argument
passing, and control. At each new level of description, we have had to
raise issues and resolve ambiguities that were not apparent at the
previous, less precise treatment of evaluation. To understand the
behavior of the explicit-control evaluator, we can simulate it and
monitor its performance.
#+END_QUOTE
