# Site settings
name: "SICP"
title: Exercises and Notes
email: correl@gmail.com
description:
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalinks: pretty

collections:
  org:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      author: "Correl Roush"
